TheBrainFamily/cypress-cucumber-preprocessor

index.js, package.json
I took the original code and implemented it as browserify transform. This way we don't need to write temporary files to disk and we can leverage `@cypress/browserify-preprocessor`'s handling of watchers and reloading. (ref #1)
I've also made the preprocessor accept options to be passed down to browserify.
Note: I've used the airbnb style simply because that's what I usually have set up. If you prefer a different style, let me know and I'll make the changes (maybe add an `.eslintrc` to the repo?)
=> implement as transform

index.js
In case we are using a custom folder configuration, we use the 'fileServerFolder' option from cypress.json to find the step_definition folders.
In case the variable is not set, then fallback to defaults.
=> Allow custom dir config

createTestFromScenario.js, createTestsFromFeature.js, package-lock.json, package.json, resolveStepDefinition.test.js
This is a proof of concept / illustration regardin the issue #43 . It is not meant to be merged right now or as-is, but this issue may force me to abandon cypress so i'd like this proposal to be considered.
I've put a cy.log() command to mark the start of each step, but this is not as good as before wrt reporting. Once cypress-io/cypress#686 is implemented, it should be possible to go back to separate tests by controlling the state clearing within a scenario. In the meantime, I think this is the only way to use gherkin + cypress in my use case (keep state between tests), and it's very likely that other people will run into the same issue.
=> fix(cypress): Merge all steps of a scenario into a single test.

cypress/integration/CustomParameterTypes.feature, cypress/support/step_definitions/customParameterTypes.js, index.js, resolveStepDefinition.js, resolveStepDefinition.test.js
This PR allows to add custom parameter types like it's defined in the [Cumcumber's documentation](https://docs.cucumber.io/cucumber/cucumber-expressions/#custom-parameter-types).
To do this, use the `defineParameterType` function into your step definitions file like that:
```js
defineParameterType({
name: 'ordinal',
regexp: /(\d+)(?:st|nd|rd|th)/,
transformer(s) {
return parseInt(s, 10);
},
})
```
=> Handle custom parameter types

README.md
It turns out the typescript setup can be accomplished with less effort than what was previously in the README. I also included a comment note about using a custom `tsconfig.json` file for the cypress tests.
=> Simplify typescript setup instructions

.eslintrc, README.md, lib/getStepDefinitionsPaths.js, lib/getStepDefinitionsPaths.test.js, package-lock.json, package.json
=> feat(step_definition): Add option to define path for the common folder

cypress/integration/AndAndButSteps.feature, cypress/support/step_definitions/and_and_but_steps.js, lib/loader.js, lib/resolveStepDefinition.js, lib/resolveStepDefinition.test.js, resolveStepDefinition.js, steps.js
I added support for and() and but() step definition to close this little gap from #82 
I'm not a master in the node/npm space. So i was not able to get the tests run, because the tests are pointing to an "installed" cypress-cucumber-prepocessor, and not to the source itself.
i've gut the jest test running (change some require temporarily) but was not able to run the cypress test. So please keep that in mind (in the meantime i saw the circle ci will take care of that).
=> and and but step definition support #82

cypress/integration/DefineStep.feature, cypress/support/step_definitions/usingDefineSteps.js, lib/loader.js, lib/resolveStepDefinition.js, lib/resolveStepDefinition.test.js, steps.js
As a step could be used with different keywords, like Given and When for example, defineStep will allow to create a step without linking it to a unique keyword in the code.
Related to https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/172.
=> Adds defineStep method

lib/loader.js
partial fix for https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/192
Accidentally changed the loader function definition with the cucumber.json PR - revert to previous way it was called to sort out the 'this' resolution when called from webpack.
**Note**: there are still issues with the typescript webpack example due to the use of the jsonFormatter module browser side
To fix this and get the typescript webpack example running again I had to identify some modules in the webpack config in that example as empty
```
module.exports = {
resolve: {
extensions: [".ts", ".js"]
},
node: { fs: "empty", child_process: "empty", readline: "empty" },  <--- fixes the webpack example
module: {
rules: [
{
test: /\.ts$/,
exclude: [/node_modules/],
use: [
{
loader: "ts-loader"
}
]
},
{ …
```
=> resourcePath no longer passed into loader from webpack correctly

README.md, lib/createTestFromScenario.js, lib/loader.js, lib/resolveStepDefinition.js, lib/testHelpers/setupTestFramework.js, steps.js
Differentiate between Before as a cucumber Hook and before as the cypress mocha hook. This PR allows both to be defined and invoked appropriately.
Also fix the issues with mocha before and after hooks getting called multiple times https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/214#issuecomment-524078837. Changed the loader to wrap the required imports into the describe block for the generated testsuite.
There is a sample repo to illustrate the results on hook invocation of this PR at https://github.com/jcundill/cypressHooks.git
Note: For global step definitions all mocha hooks are at the Global scope - so beforeEach applies to all scenarios, etc. As the support pages are included into the cypress runner outside of any test scopes.
For local step definitions, mocha …
=> Stop cucumber Before hook clobbering mocha before.

lib/cukejson/cucumberDataCollector.js
This is added in addition to the stack trace when an error is thrown.
Adds no value and crashes on non latin text.
Fixes https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/221
=> Remove the text/plain error attachment from the cucumber report

README.md
Removed comment about backtick limitations in WebStorm as this is no longer true. String based cucumber expressions and regexes work fine post 2019.2.
Added notes about how to enable step resolution support in both Visual Studio Code and Intellij IDEA as there have recently been a bunch of questions around this.
=> Updated README IDE support notes.

lib/cukejson/cucumberDataCollector.js
I found this to be pretty useful when trying to pinpoint where each step actually happens in my logs. Otherwise I find that the LOG of each step gets lost amongst all of the other logs a bit. Figured I'd open this PR if other people found this useful and wanted to incorporate it as a feature.
=> Bold console.log when logging each step

lib/cypressExecutionInstance.js, lib/index.js, lib/stepDefinitionPath.js, lib/stepDefinitionPath.test.js, package-lock.json, package.json
When Cypress it's running when the `--config-file` flag, the preprocessor cannot find the path configured by this flag because in `lib/stepDefinitionPath.js` the `cypress.json` always loaded from the appRoot.
=> feature (get-cypress-config): allow check if cypress were run using --config-file option and use the configured path for get cypress config

cypress-tags.js
Adding conditions to avoid features running if no matching tags are found. 
Currently, if I run `./node_modules/.bin/cypress-tags run -e TAGS='@undefined-tag'`, with `@undefined-tag` absent from every .feature file, all the features all launched : 
See line 61 of cypress-tags.js :
```js
[...process.argv.slice(2), "--spec", featuresToRun.join(",")]
```
Currently, if there are no matching features found, `featuresToRun.join(",")` returns empty string, so features are not filtered.
=> fix(tags): adding conditions to avoid features running if no matching tags are found

README.md
Fixed a typo and changed redundant wording on last update... Also, probably the link from the table of comments seems to be failing... anyone can check it?
=> Fix type and wording on Readme.md

README.md
What's new ?
Add a subsection in the documentation section of typescript to explain the user that he have to install typescript plugin types.
Feel free to edit/not merge... :-)
Have a nice day.
=> add typescript install type definitions to doc

lib/createTestFromScenario.js, lib/createTestsFromFeature.js, lib/cukejson/cucumberDataCollector.js, lib/testHelpers/setupTestFramework.js
Addresses https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/288
Currently skipped tests, those not matching the tags used for the run, are not added to the cucumber.json files generated during that run.
This PR adds them back into the generated files.
Changes:
In `createTestsFromFeature` pass all the scenarios into `createTestFromScenarios` but mark the subset that should actually be executed with a `shouldRun` flag.
In `createTestFromScenarios` check if the scenario should be executed and if not just add it to the `cucumberDataCollector` and tell `mocha` that we skipped this test.
Fix the `cucumberDataCollector` not to fail the scenario if `mocha` tells it that the test was skipped.
=> Skipped Scenarios missing from cucumber.json files #288

lib/createTestFromScenario.js, lib/resolveStepDefinition.js, lib/testHelpers/setupTestFramework.js, steps/index.d.ts
Add support for passing in a config param, matching the signature of cucumber-js, to set the step
timeout in cypress.
e.g.
```
Given('a long running step', { timeout: 60000 }, () => { ... });
```
It is possible to do this by calling `cy.then({timeout: 60000}, () => {...})` inside the implementation function, but that's inconsistent with [the signature for cucumberjs](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/timeouts.md#timeouts), which feels more intuitive.
=> feat: add support for custom step timeout

cypress-tags.js, package-lock.json
This sets it to respect how Cypress expect and behaves with this flag allowing us to pass
environment varibles along side TAGS and GLOB and have all variables be properly passed to Cypress.
fixes #335
fixes #244
=> Corrected parsing of passed environment variables for GLOB and TAGS

README.md, lib/getStepDefinitionsPaths.js, lib/getStepDefinitionsPaths.test.js
Within my team we have a preference to split the step definitions away from where the feature files are located.
However we love the ability to scope test definitions so using the common folder and global approach doesn't seem right.
To this end I have created a PR that if you agree adds a new configuration option `nonGlobalStepBaseDir` which defines a location from which the feature files folders are matched from. If it is not set then the current behaviour is maintained.
=> feat(getstepdefinitionspaths): configurable nonGlobalStepDefinitions base directory

.github/ISSUE_TEMPLATE.md
Subject says it all.
Too many issues are reported with little to no possibility of reproducing the problem, at least not without significant effort.
=> Add an issue template in an attempt to gather info more efficiently

lib/featuresLoader.js, package-lock.json
I have tried with our project (80+ scenarios) they now seem to work.
tests in the repo also pass (some dont because of windows vs linux path slashes, but that was the case before)
#304
=> fix(nonGlobalStepDefinitions): .features files now work with webpack

lib/getStepDefinitionsPaths.js, lib/getStepDefinitionsPaths.test.js
fix the issue: when `nonGlobalStepBaseDir` is defined, and `nonGlobalStepDefinitions` is true, default `commonPath` is not correct and it is not `${nonGlobalStepBaseDir}/${commonPath}`
=> fix: define commonPath based on nonGlobalStepBaseDir.

cypress/integration/DocString.feature, cypress/support/step_definitions/docString.js, lib/featuresLoader.js, lib/loader.js
Test case for reported issue https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/415
DocString.feature will fail when ES6 template literals are present in the DocString.
Open to suggestions/support on how this can be fixed.
=> fix(docstring.feature): extend DocString.feature tests to cover failing scenario

README.md, circle.yml, package-lock.json, package.json
Cypress v4.4.0 supports TypeScript without additional preprocessors (https://github.com/cypress-io/cypress/issues/1859).
These are the instructions for setting that up with the Cucumber preprocessor. Which, granted, are very similar to the tsify solution but require less additional dependencies.
I'm submitting this for consideration, but have to make the note that this is blocked by https://github.com/cypress-io/cypress-browserify-preprocessor/issues/56, so merging will probably have to wait until that issue is resolved.
=> Add instructions for 'out-of-the-box' TypeScript support

cypress-tags.js
BREAKING CHANGE: Glob pattern is no longer "cypress/integration/**/*.feature", but is now based on cypress.json configuration by default, and takes into account the ignoreTestFiles
(fallback to cypress/integration/**/*.feature if there is any error)
If the GLOB option is specified, Cypress configuration will be ignored, and the features will only match this option.
=> feat(tags): improve the tags behavior, to base on cypress configuration

lib/getStepDefinitionsPaths.js, lib/getStepDefinitionsPaths.test.js, lib/index.js
This may be a (very) niche use case but I use a custom flavour of JSX in my step files to create initial data for a test.
=> feat(getstepdefinitionpaths.js): allow tsx extension for step definition files

cypress/integration/DocString.feature, cypress/support/step_definitions/docString.js, lib/resolveStepDefinition.js
Add the functionality that the preprocessor also translates/replaces arguments in `DocString`.
This is a Documented Cucumber Feature:
https://github.com/yuyijq/cucumber/wiki/Multiline-Step-Arguments#substitution-in-scenario-outlines
=> fix: support multiline step arguments

package-lock.json, package.json
Bump chokidar from 2.1.8 to 3.5.1 due to a vulnerability in its transient dependency glob-parent (fixed in version 5.1.2)
=> bump chokidar from 2.1.8 to 3.5.1

cypress-tags.js
Now the script supports filtering examples of scenario outlines too. I have removed the optimization
that we should check scenario tags if there are any, because they do not work for negated tags (e.g.
`not @tag1`). Additionally, just checking the feature tag itself is also wrong, because a feature
with tag `@feature` having a scenario with tag `@scenario` would incorrectly run when we filter for
`not @scenario`. So the best is to leave the tag checking for "leaf nodes", i.e. scenarios or
examples. Also consider the corner case where a feature has no scenarios or scenario outlines at
all, i.e. again we would not run such a feature at all.
Fixes #196.
=> fix(cypress-tags.js): scenario outlines with examples were not correctly filtered by tags

package-lock.json, package.json
As per the release notes,
https://github.com/cypress-io/cypress-browserify-preprocessor/releases/tag/v3.0.2.
@cypress/browserify-preprocessor has updated their dependencies to fix this issue
fix #618
=> chore(deps): [security] bump @cypress/browserify-preprocessor from 3.0.1 to 3.0.2

README.md
The typescript support that is documented is only running until Cypress 8.5.0. As of Cypress version 8.6.0 it should be done in another way without using `resolve.sync()`. But this new solution is also working with Cypress version <= 8.5.0 and of course also for higher versions.
=> update documentation for typescript support
