cypress/integration/RequiringFiles.feature
cypress/integration/UsingAnd.feature
cypress/support/step_definitions/requiringFiles.js
cypress/support/step_definitions/requiringFilesData.js
cypress/support/step_definitions/usingAnd.js
index.js
package-lock.json
package.json
resolveStepDefinition.js

Fixing #31 #30 #28 #16

---

cypress/integration/WebstormSupport.feature
cypress/support/step_definitions/webstormSupport.steps.js
index.js

Here's the new PR without package-lock.json

Webstorm support pr

---

createTestFromScenario.js

Display variable names in scenario outlines instead of placeholder

---

README.md

Add background section to documentation

---

lib/createTestsFromFeature.js

fix: feature tags

---

cypress/integration/ScenarioOutline.feature
cypress/support/step_definitions/scenario_outline_data_table.js
lib/createTestFromScenario.js
lib/resolveStepDefinition.js
lib/resolveStepDefinition.test.js
package-lock.json
package.json

This PR fixes https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/137.
@lgandecki could you have a look, if this might do already.
Thanks in advance!

Scenario outline and data tables

---

lib/resolveStepDefinition.js

I wanted to clean up the code regarding the scenario outlines and datatables, to make it more understandable

Clean up scenario outline code

---

lib/tagsHelper.js

fix: make sure that when using 'not @tag', we do run features that do not have any tags

fix: handing of "not" tag expressions

---

cypress/integration/WebstormSupport.feature

Fix scenario typo in WebstormSupport.feature

Fix typo in WebstormSupport.feature

---

cypress/integration/ScenarioOutline.feature
cypress/support/step_definitions/scenario_outline_multiple_vars.js
lib/createTestFromScenario.js
lib/resolveStepDefinition.test.js

fix scenario outline examples variable multiple times in single step

---

lib/cukejson/cucumberDataCollector.js

closes [https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/225](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/225)

fix: check if error message exists on fail

---

package-lock.json
package.json

bumped the dependency for cypress browserify preprocessor

---

cypress/integration/DataTable.feature
cypress/support/step_definitions/dataTable.js
lib/featuresLoader.js
lib/loader.js
package-lock.json
package.json

We will now parse and escape the stringified .feature file when putting it in the template literal -
otherwise the escaped characters got parsed and we were getting syntax errors
fix #106

fix(loader): work with escaped characters

---

README.md

Me again... :D fixed link to new "ignore tests" section from TOC, which was not working

Fix hyperlink from TOC

---

cypress-tags.js

fix(tags): allow empty feature files

---

lib/index.js
lib/index.test.js

Address cases where options passed to preprocessor would result in a TypeError

---

cypress-tags.js

feat(tags): make the TAGS env. variable optional

---

lib/createTestFromScenario.js
lib/cukejson/cucumberDataCollector.js
lib/cukejson/cucumberDataCollector.test.js
lib/cukejson/generateCucumberJson.js

fix: import exactly what we need from cucumber to avoid bringing node-related dependencies

---

README.md

Update README.md to show links to data table examples

---

steps/index.d.ts

fix(types): getting the types up to date

---

README.md

"https://google.com" title is "Google" not "google"

docs(README): fix example failed

---

cypress/integration/BeforeAndAfterSteps.feature
cypress/integration/TagsImplementationWithEnvSetExamplesLevel.feature
lib/createTestFromScenario.js
lib/createTestsFromFeature.js

According to cucumber tags should be inherited downwards. See
https://cucumber.io/docs/cucumber/api/#tags
fix #196

fix(tags): fix inheritance according to cucumber specs
